os:
  editPreset: "nvim-remote"
gui:
  nerdFontsVersion: "3"
  theme:
    unstagedChangesColor:
      - "#fb4934"
    selectedLineBgColor:
      - "#665c54"
    searchingActiveBorderColor:
      - "bold"
    optionsTextColor:
      - "#fabd2f"
    inactiveBorderColor:
      - "#ebdbb2"
    defaultFgColor:
      - "#ebdbb2"
    cherryPickedCommitFgColor:
      - "#fabd2f"
    cherryPickedCommitBgColor:
      - "#83a598"
    activeBorderColor:
      - "bold"
